
package GUI.SubPantallasCorredores;

import Logica.Lista_Corredores;
import DTO.Corredor;
import GUI.SubPantallasCorredores.Tablemodels.Tablemodels;
import java.util.*;
import java.text.*;
import javax.swing.JOptionPane;

public class Corredores extends javax.swing.JDialog {
    
    /* Creamos un binculo a la lista de corredores */
    private Lista_Corredores lista_Corredores = new Lista_Corredores();
    /* Este atributo se usa para recojer los datos de los corredores a borrar o a modificar */
    private Corredor MouseClicked;

    /* Creates new form Corredores */
    public Corredores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ActualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_DNI = new javax.swing.JLabel();
        jLabel_Fecha = new javax.swing.JLabel();
        jLabel_Direcion = new javax.swing.JLabel();
        jLabel_Telefono = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_DNI = new javax.swing.JTextField();
        jSpinner_Fecha_Nacimiento = new javax.swing.JSpinner();
        jTextField_Direcion = new javax.swing.JTextField();
        jTextField_N_Contacto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton_Añadir = new javax.swing.JButton();
        jButton_Borrar = new javax.swing.JButton();
        jButton_Modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Nombre.setText("Nombre:");

        jLabel_DNI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_DNI.setText("DNI:");

        jLabel_Fecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Fecha.setText("Fecha nacimiento:");

        jLabel_Direcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Direcion.setText("Direción:");

        jLabel_Telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Telefono.setText("Telefono:");

        jSpinner_Fecha_Nacimiento.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Nombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_DNI))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Direcion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Direcion))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_N_Contacto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner_Fecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_Fecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Direcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Direcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_N_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Añadir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Añadir.setText("Añadir");
        jButton_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AñadirActionPerformed(evt);
            }
        });

        jButton_Borrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Borrar.setText("Borrar");
        jButton_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BorrarActionPerformed(evt);
            }
        });

        jButton_Modificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Modificar.setText("Modificar");
        jButton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Añadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Modificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Datos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Datos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /* Añadir corredor a la lista de corredores de paquete Logica donde esta el ArrayList */
    
    private void jButton_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AñadirActionPerformed
        /* Cojemos los datos llamandoa al metodo Recojer_Datos */
        Corredor c = Recojer_Datos();
        /* Añadimos al corredor a la lista */        
        lista_Corredores.Añadir_Participante(c);
        /* Actualizamos la tabla y los campos de texto */
        ActualizarTabla();
        Actualizar_Campos();
    }//GEN-LAST:event_jButton_AñadirActionPerformed
    
    /* Borramos al corredor selecionado por el evento de MouseClicked de la tabla */
    
    private void jButton_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BorrarActionPerformed
        /* Confirmamos que quiere borrar al usuario */
        String Yes_No = "Confirma para borrar al corredor " + MouseClicked.getNombre();
        int resultado = JOptionPane.showConfirmDialog(this, Yes_No, "Confirmar", JOptionPane.YES_NO_OPTION);
        if(resultado == JOptionPane.YES_OPTION){
            /* Llamamos al metodoa de borrar */
            lista_Corredores.Borrar_Participante(MouseClicked);
            /* Informamos de estado */
            JOptionPane.showMessageDialog(this, "El corredor fue borrado con exito", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            /* Actualizamos la tabla */
            ActualizarTabla();
        } else {
            /* Informamos que no se borrara el corredor */
            JOptionPane.showMessageDialog(this, "El corredor no fue borrado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        /* Actualizamos campos de texto y asignamos balor null al atributo MouseClicked */ 
        Actualizar_Campos();
        MouseClicked = null;
    }//GEN-LAST:event_jButton_BorrarActionPerformed

    /* Actualizamos al corredor selecionado por el evento de MouseClicked de la tabla */
    
    private void jButton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarActionPerformed
        /* Confirmamos que quiere modificar al usuario */
        String Yes_No = "Confirma para modificar al corredor " + MouseClicked.getNombre();
        int resultado = JOptionPane.showConfirmDialog(this, Yes_No, "Confirmar", JOptionPane.YES_NO_OPTION);
        if(resultado == JOptionPane.YES_OPTION){
            /* Cojemos los datos llamandoa al metodo Recojer_Datos y se lo pasamos al metodo de modificar */
            Corredor c_Nuevo = Recojer_Datos();
            lista_Corredores.Actualizar_Participantes(MouseClicked, c_Nuevo);
            /* Actualizamos la tabla */
            ActualizarTabla();
            /* Informamos de estado */
            JOptionPane.showMessageDialog(this, "El corredor fue actualizado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        } else{
            JOptionPane.showMessageDialog(this, "El corredor no fue actualizado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        /* Actualizamos campos de texto y asignamos balor null al atributo MouseClicked */ 
        Actualizar_Campos();
        MouseClicked = null;
    }//GEN-LAST:event_jButton_ModificarActionPerformed

    /* Selecionar corredor a modificar o a borrar */
    
    private void jTable_DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DatosMouseClicked
        /* Cojemos la fila donde icimos click */
        int seleccion = jTable_Datos.rowAtPoint(evt.getPoint());
        /* Cojemos los valores de esa fila y los recolocamos en los JTextField o jSpinner*/
        jTextField_Nombre.setText(String.valueOf(jTable_Datos.getValueAt(seleccion, 0)));
        jTextField_DNI.setText(String.valueOf(jTable_Datos.getValueAt(seleccion, 1)));
        /* Convertimos la fecha optenida de String a date y se la pasamos al jSpinner */
        try{
            String Fecha = String.valueOf(jTable_Datos.getValueAt(seleccion, 2));
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            jSpinner_Fecha_Nacimiento.setValue(sdf.parse(Fecha));
        } catch (ParseException e){
            System.out.println(e.getMessage());
        }
        jTextField_Direcion.setText(String.valueOf(jTable_Datos.getValueAt(seleccion, 3)));
        jTextField_N_Contacto.setText(String.valueOf(jTable_Datos.getValueAt(seleccion, 4)));
        /* Cojemos los datos llamandoa al metodo Recojer_Datos y los guardamos en el atrivuto */
        MouseClicked = Recojer_Datos();
    }//GEN-LAST:event_jTable_DatosMouseClicked
    
    /* Este metodo recoje los datos de la tabla */
    
    private Corredor Recojer_Datos(){
        /* Cojemos los datos introducidos */
        String Nombre = jTextField_Nombre.getText();
        String DNI = jTextField_DNI.getText();
        Date Fecha_Nacimiento = (Date) jSpinner_Fecha_Nacimiento.getValue();
        String Direcion = jTextField_Direcion.getText();
        int N_Contacto = Integer.valueOf(jTextField_N_Contacto.getText());
        /* Creamos al corredor */
        return new Corredor(Nombre, DNI, Fecha_Nacimiento, Direcion, N_Contacto);
    }
    
    /* Este metodo restaurarra los campos a sus balores por defecto */
    
    private void Actualizar_Campos (){
        jTextField_Nombre.setText("");
        jTextField_DNI.setText("");
        jSpinner_Fecha_Nacimiento.setValue(new Date());
        jTextField_Direcion.setText("");
        jTextField_N_Contacto.setText("");
    }
    
    /* Este metodo sirbe para actualizar la tabla */
    
    private void ActualizarTabla (){
        jTable_Datos.setModel(new Tablemodels(lista_Corredores.getLista_Participantes()));
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Añadir;
    private javax.swing.JButton jButton_Borrar;
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JLabel jLabel_DNI;
    private javax.swing.JLabel jLabel_Direcion;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_Fecha_Nacimiento;
    private javax.swing.JTable jTable_Datos;
    private javax.swing.JTextField jTextField_DNI;
    private javax.swing.JTextField jTextField_Direcion;
    private javax.swing.JTextField jTextField_N_Contacto;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
