
package GUI.SubPantallaCarreras;

import DTO.Carrera;
import Logica.Lista_Carreras;
import GUI.SubPantallaCarreras.Tablemodels.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Carreras_Realizadas extends javax.swing.JDialog {

    /* Creamos un binculo a la lista de carreras */
    private Lista_Carreras lista_carreras = new Lista_Carreras();
    /* Esto es para pasar los resultados de la carrera */
    private Carrera c = new Carrera();
    
    /* Creates new form Carreras_Realizadas */
    public Carreras_Realizadas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Actualizar_Tabla_Carreras();
        Actualizar_Tabla_Resultados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Carreras:");

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarrerasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCarreras);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Resultados:");

        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarrerasMouseClicked
        /* Cojemos la fila donde icimos click */
        int seleccion = jTableCarreras.rowAtPoint(evt.getPoint());
        /* Cojemos los valores de esa fila y los recolocamos en los JTextField o jSpinner*/
        String nombre = String.valueOf(jTableCarreras.getValueAt(seleccion, 0));
        /* Convertimos la fecha optenida de String a date y se la pasamos al jSpinner */
        Date fecha = null;
        try{
            String Fecha = String.valueOf(jTableCarreras.getValueAt(seleccion, 1));
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            fecha = sdf.parse(Fecha);
        } catch (ParseException e){
            System.out.println(e.getMessage());
        }
        if(fecha != null){
            c = lista_carreras.Buscar_Resultados(nombre, fecha);
            c.Ordenar_Resultados();
        }
        Actualizar_Tabla_Resultados();
    }//GEN-LAST:event_jTableCarrerasMouseClicked

    public void Actualizar_Tabla_Carreras(){
        jTableCarreras.setModel(new Tablemodels(lista_carreras.Lista_Carreras_Realizadas()));
    }
    
    public void Actualizar_Tabla_Resultados(){
        jTableResultados.setModel(new Tablemodels_Resultados(c.getLista_Corredores()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCarreras;
    private javax.swing.JTable jTableResultados;
    // End of variables declaration//GEN-END:variables
}
